CHG: Improved sanity checks

diff --git a/bin/dnuclearizer b/bin/dnuclearizer
--- a/bin/dnuclearizer
+++ b/bin/dnuclearizer
@@ -30,6 +30,7 @@ commandhelp() {
   echo "  --delay=[number] Time between searches for free slots -- the longer the delay time the lower the priority of this instance (default: 10 seconds)"
   echo "  --zip: Compress the output files."
   echo "  --log: Create a log file of what is started where"
+  echo "  --test: Perform a test run up until actually starting the instances"
   echo "  --help: Show this help."
   echo ""
   echo "";
@@ -71,6 +72,7 @@ LOGFILE=""
 LOGGING="tee"
 DELAY="10"
 CFG=~/.dcosima.cfg
+TESTRUN="FALSE"
 
 # Response creator specific options
 NUCLEARIZERCFG=""
@@ -88,7 +90,7 @@ HERE=$(pwd)
 for C in "${CMD[@]}"; do
   if [[ ${C} == *-d*=* ]]; then
     DATADIR=$( cut -d '=' -f 2- <<< "${C}" )
-  elif [[ ${C} == *-t*=* ]]; then
+  elif [[ ${C} == *-ta*=* ]]; then
     TARGETDIR=$( cut -d '=' -f 2- <<< "${C}" )
   elif [[ ${C} == *-cont* ]]; then
     CONTINUE="TRUE"
@@ -98,6 +100,8 @@ for C in "${CMD[@]}"; do
     DELAY=$( cut -d '=' -f 2- <<< "${C}" )
   elif [[ ${C} == *-l* ]]; then
     LOG="TRUE"
+  elif [[ ${C} == *-te* ]]; then
+    TESTRUN="TRUE"
   elif [[ ${C} == *-cfg*=* ]]; then
     NUCLEARIZERCFG=$( cut -d '=' -f 2- <<< "${C}" )
   elif [[ ${C} == *-h* ]]; then
@@ -137,7 +141,7 @@ fi
 # Check if we have read access
 if [ ! -r ${DATADIR} ]; then
   echo " "
-  echo "ERROR: You need to have read access to the data directory"
+  echo "ERROR: You need to have read access to the data directory: ${DATADIR}"
   exit 1
 fi
 echo " * Data directory: ${DATADIR}"
@@ -151,7 +155,7 @@ fi
 # Check if we have read and write access
 if [ ! -r ${TARGETDIR} ] || [ ! -w ${TARGETDIR} ]; then
   echo " "
-  echo "ERROR: You need to have read and write access to the target directory"
+  echo "ERROR: You need to have read and write access to the target directory: ${TARGETDIR}"
   exit 1
 fi
 
@@ -301,6 +305,7 @@ while [[ $d -lt ${#DATAFILES[*]} ]]; do
   
   # Verify the machines:
   AVAILABLEMACHINES=0
+  MACHINEERRORS="FALSE"
   echo " " | ${LOGGING}
   echo "Verifying available machines: " | ${LOGGING}
   for (( m=0; m<=$(( ${#MACHINES[*]} -1 )); m++ )); do
@@ -312,6 +317,7 @@ while [[ $d -lt ${#DATAFILES[*]} ]]; do
     if [ "$?" != "0" ]; then
       echo " * Remote machine: ${MACHINES[$m]}: NOT ACCESSIBLE OR TOO SLOW TO ANSWER" | ${LOGGING}
       MACHINES[$m]=""
+      MACHINEERRORS="TRUE"
       continue
     else
       echo " * Remote machine: ${MACHINES[$m]}: Accessible" | ${LOGGING}
@@ -333,46 +339,59 @@ while [[ $d -lt ${#DATAFILES[*]} ]]; do
     if [[ $? == "124" ]]; then
       echo " * Remote machine: ${MACHINES[$m]}: WARNING: Slow connection - skipping this machine for this round of launches." | ${LOGGING}
       MACHINES[$m]=""
+      MACHINEERRORS="TRUE"
       continue
     fi      
     if [[ ${ANSWER} == "" ]]; then ANSWER="ERROR: Check failed with the above error!"; fi
     if [[ ${ANSWER} != "Available" ]]; then     
       echo " * Remote machine: ${MACHINES[$m]}: ${ANSWER}" | ${LOGGING}
       MACHINES[$m]=""
+      MACHINEERRORS="TRUE"
       continue
     fi
  
     echo " * Remote machine: ${MACHINES[$m]}: ${ANSWER}" | ${LOGGING}
     
-    if [[ ${FIRSTTEST} == "TRUE" ]]; then
-      COMMAND=""
-      COMMAND+=". .bash_local;"
-      COMMAND+="cd ${TARGETDIR};"
-      COMMAND+="nuclearizer --test -m 0 -c ${NUCLEARIZERCFG} -a -n -C ModuleOptions.XmlTagSimulationLoader.SimulationFileName=${DATADIR}/${DATAFILES[0]} -C ModuleOptions.XmlTagEventSaver.FileName=Test.evta"; 
-      ANSWER=$(ssh -i ${HOME}/.ssh/dmegalib_rsa -q -o ConnectTimeout=2 -o "PreferredAuthentications=publickey" -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} 'bash -s' <<< ${COMMAND} )
-      if [[ "$?" != "0" ]]; then
-        echo " * Remote machine: ${MACHINES[$m]}: Failed to launch nuclearizer!" | ${LOGGING}
-        MACHINES[$m]=""
-        continue
-      fi
-      if [[ ${ANSWER} != *TEST*RUN*SUCCESSFUL* ]]; then     
-        echo " * Remote machine: ${MACHINES[$m]}: nuclearizer run failed" | ${LOGGING}
-        echo "" | ${LOGGING}
-	echo "---- ERROR MESSAGE ----" | ${LOGGING}
-        echo "${ANSWER}" | ${LOGGING}
-	echo "-----------------------" | ${LOGGING}
-	echo "" | ${LOGGING}
-	MACHINES[$m]=""
-        continue
-      else
-        echo " * Remote machine: ${MACHINES[$m]}: nuclearizer OK" | ${LOGGING}
-      fi    
+    COMMAND=""
+    COMMAND+=". .bash_local;"
+    COMMAND+="cd ${TARGETDIR};"
+    COMMAND+="nuclearizer --test -m 0 -c ${NUCLEARIZERCFG} -a -n -C ModuleOptions.XmlTagSimulationLoader.SimulationFileName=${DATADIR}/${DATAFILES[0]} -C ModuleOptions.XmlTagEventSaver.FileName=Test.evta"; 
+    ANSWER=$(ssh -i ${HOME}/.ssh/dmegalib_rsa -q -o ConnectTimeout=2 -o "PreferredAuthentications=publickey" -p ${REMOTEPORT[$m]} ${REMOTEUSER[$m]}@${REMOTEHOST[$m]} 'bash -s' <<< ${COMMAND} )
+    if [[ "$?" != "0" ]]; then
+      echo " * Remote machine: ${MACHINES[$m]}: Failed to launch nuclearizer!" | ${LOGGING}
+      MACHINES[$m]=""
+      MACHINEERRORS="TRUE"
+      continue
     fi
+    if [[ ${ANSWER} != *TEST*RUN*SUCCESSFUL* ]]; then     
+      echo " * Remote machine: ${MACHINES[$m]}: nuclearizer run failed" | ${LOGGING}
+      echo "" | ${LOGGING}
+      echo "---- ERROR MESSAGE ----" | ${LOGGING}
+      echo "${ANSWER}" | ${LOGGING}
+      echo "-----------------------" | ${LOGGING}
+      echo "" | ${LOGGING}
+      MACHINES[$m]=""
+      MACHINEERRORS="TRUE"
+      continue
+    else
+      echo " * Remote machine: ${MACHINES[$m]}: nuclearizer OK" | ${LOGGING}
+    fi    
     
     AVAILABLEMACHINES=$(( ${AVAILABLEMACHINES} + 1 ))
     
   done
   
+  if [[ ${TESTRUN} == "TRUE" ]]; then
+    if [[ ${MACHINEERRORS} == "FALSE" ]]; then
+      echo ">>> TEST RUN SUCCESSFUL <<<"
+      exit 0
+    else
+      echo ">>> TEST RUN FAILED <<<"
+      exit 1
+    fi
+  fi
+
+
   FIRSTTEST="FALSE"
   
   # If we have NO machines available, we quit...
