CHG: Show number of running jobs and optional test run

diff --git a/bin/mnuclearizer b/bin/mnuclearizer
--- a/bin/mnuclearizer
+++ b/bin/mnuclearizer
@@ -10,12 +10,14 @@ help() {
   echo "    -c <file name>: Nuclearizer configuration file name"
   echo "    -t <int>:       Number if threads to use"
   echo "    -f <file name>: Long list of sim or dat files"
+  echo "    -r              Perform a 10 second test run, to check for error messages"
   echo ""
   echo "Attention:"
   echo "    -f must be the last given option"
   echo ""
-  echo "Example:"
+  echo "Examples:"
   echo "    mnuclearizer -c Nuclearizer.cfg -n 19 -f RunTest*.sim"
+  echo "    mnuclearizer -r -c Nuclearizer.cfg -f Run.p1.inc{2..7}.id1.sim Run.p1.inc{10,12,13}.id1.sim"
   echo ""
   echo "This script runs multiple nuclearizer sessions in parallel. By default as many instances as the system has cores are started. But each nuclearizer run is in itself multi-threaded."
   echo ""
@@ -32,6 +34,7 @@ THREADS=1
 NICELEVEL=0
 CFG=""
 FILES=""
+TEST="FALSE"
 
 # Find the default number of threads
 if [[ ${OSTYPE} == darwin* ]]; then
@@ -54,6 +57,9 @@ while [ $# -gt 0 ] ; do
   -h|--help)
     help;
     exit 0;;
+  -r)
+    TEST="TRUE"
+    ;;
   -t)
     shift;
     if [ $# -eq 0 ]; then
@@ -155,6 +161,17 @@ if [[ ! -f ${CFG} ]]; then
   exit 1;
 fi
 
+if [[ ${FILES} == "" ]]; then
+  echo " "
+  echo "Error: You need to provide data files for mnuclearizer as last argument."
+  echo " "
+  rm /tmp/aux
+  exit 1;
+fi
+# REmove leading white space:
+FILES="$(echo -e "${FILES}" | sed -e 's/^[[:space:]]*//')"
+
+
 echo " "
 echo "Launching mnuclearizer"
 echo " "
@@ -162,6 +179,32 @@ echo "Number of threads to use:  ${THREADS}"
 echo "Nice level:                ${NICELEVEL}"
 echo "Configuration file:        ${CFG}"
 echo "Input files:               ${FILES}"
+echo " "
+echo " "
+
+if [[ ${TEST} == "TRUE" ]]; then
+  echo "Launching test run..."
+  SIMFILE=${FILES%% *}
+  if [[ ${SIMFILE} == *.sim ]] || [[ ${SIMFILE} == *.sim.gz ]]; then
+    OUT=$( timeout 10s nuclearizer -m 0 -c ${CFG} -a -n -C ModuleOptions.XmlTagSimulationLoader.SimulationFileName=${SIMFILE} -C ModuleOptions.XmlTagEventSaver.FileName=$(basename ${SIMFILE} | sed s/.sim/.evta/g) 2>&1 )
+  elif [[ ${SIMFILE} == *.dat ]] || [[ ${SIMFILE} == *.dat.gz ]]; then
+    OUT=$( timeout 10s nuclearizer -m 1 -c ${CFG} -a -n -C ModuleOptions.XmlTagMeasurementLoaderBinary.FileName=${SIMFILE} -C ModuleOptions.XmlTagEventSaver.FileName=$(basename ${SIMFILE} | sed s/.dat/.evta/g) 2>&1 )
+  fi
+  ERROR=$(echo ${OUT} | grep -i -e "ERROR" -e "FATAL")
+  if [[ ${ERROR} != "" ]]; then
+    echo " "
+    echo "ERROR: Unable to perform a nuclearizer test run. Error message:"
+    echo " "
+    echo "${OUT}"
+    echo " "
+    echo " "
+
+    exit 1
+  fi
+  echo " "
+  echo " "
+fi
+
 
 
 # Now run, nuclearizer RUN!
@@ -170,9 +213,9 @@ for SIMFILE in ${FILES}; do
   echo "Launching nuclearizer for file ${SIMFILE}"
   if [[ ${SIMFILE} == *.sim ]] || [[ ${SIMFILE} == *.sim.gz ]]; then
     #nuclearizer -m 0 -c ${CFG} -a -n -C ModuleOptions.XmlTagSimulationLoader.SimulationFileName=${SIMFILE} -C ModuleOptions.XmlTagEventSaver.FileName=$(basename ${SIMFILE} | sed s/.sim/.evta/g)
-    nohup nice -n ${NICELEVEL} bash -c "source ${MEGALIB}/bin/source-megalib.sh; nuclearizer -m 1 -c ${CFG} -a -n -C ModuleOptions.XmlTagSimulationLoader.SimulationFileName=${SIMFILE} -C ModuleOptions.XmlTagEventSaver.FileName=$(basename ${SIMFILE} | sed s/.sim/.evta/g)" > /dev/null &
+    nohup nice -n ${NICELEVEL} bash -c "source ${MEGALIB}/bin/source-megalib.sh; nuclearizer -m 1 -c ${CFG} -a -n -C ModuleOptions.XmlTagSimulationLoader.SimulationFileName=${SIMFILE} -C ModuleOptions.XmlTagEventSaver.FileName=$(basename ${SIMFILE} | sed s/.sim/.evta/g)" 2> /dev/null &
   elif [[ ${SIMFILE} == *.dat ]] || [[ ${SIMFILE} == *.dat.gz ]]; then
-    nohup nice -n ${NICELEVEL} bash -c "source ${MEGALIB}/bin/source-megalib.sh; nuclearizer -m 1 -c ${CFG} -a -n -C ModuleOptions.XmlTagMeasurementLoaderBinary.FileName=${SIMFILE} -C ModuleOptions.XmlTagEventSaver.FileName=$(basename ${SIMFILE} | sed s/.dat/.evta/g)" > /dev/null &  
+    nohup nice -n ${NICELEVEL} bash -c "source ${MEGALIB}/bin/source-megalib.sh; nuclearizer -m 1 -c ${CFG} -a -n -C ModuleOptions.XmlTagMeasurementLoaderBinary.FileName=${SIMFILE} -C ModuleOptions.XmlTagEventSaver.FileName=$(basename ${SIMFILE} | sed s/.dat/.evta/g)" 2> /dev/null &  
   else 
     echo " "
     echo "Error: The data file must be a sim(.gz) or .dat(.gz) file";
@@ -181,10 +224,15 @@ for SIMFILE in ${FILES}; do
   fi
   sleep 2
 done
+echo " "
 
 
 # We always wait until all nuclearizer runs have finished
-echo "Waiting till all nuclearizer runs have finished..."
-wait
+JOBS=$( jobs -p -r )
+until [[ ${JOBS} == "" ]]; do
+  echo "Currently $(echo ${JOBS} | wc -w) jobs are running. Waiting till all have finished."
+  sleep 10
+done
+echo "All jobs have finished"
 
 exit 0;
